name: FISys
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobile_vision_2: ^0.1.15
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  syncfusion_flutter_datepicker: ^23.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
